export enum CLOTHING_IDS_LIST {
    HEAD = 0,
    MASKS = 1,
    HAIR_STYLES = 2,
    TORSOS = 3,
    LEGS = 4,
    BAGS = 5,
    SHOES = 6,
    ACCESSORIES = 7,
    UNDERSHIRTS = 8,
    BODY_ARMOUR = 9,
    DECALS = 10,
    TOP = 11,
}

export enum PROP_IDS_LIST {
    HATS = 0,
    GLASSES = 1,
    EARS = 2,
    MOUTH = 3,
    LEFT_HAND = 4,
    RIGHT_HAND = 5,
    WATCHES = 6,
    BRACELETS = 7,
    HIP = 8,
    LEFT_FOOT = 9,
    RIGHT_FOOT = 10,
    PH_LEFT_HAND = 11,
    PH_RIGHT_HAND = 12,
    NUM_ANCHORS = 13,
}
